version: '3'

services:

  configsvr1:
    container_name: configsvr1
    image: mongo
    command: mongod --configsvr --replSet configsvrrs --dbpath /data/db --port 27017
    ports:
      - 40001:27017
    volumes:
      - configsvr1:/data/db

  configsvr2:
    container_name: configsvr2
    image: mongo
    command: mongod --configsvr --replSet configsvrrs --dbpath /data/db --port 27017
    ports:
      - 40002:27017
    volumes:
      - configsvr2:/data/db

  configsvr3:
    container_name: configsvr3
    image: mongo
    command: mongod --configsvr --replSet configsvrrs --dbpath /data/db --port 27017
    ports:
      - 40003:27017
    volumes:
      - configsvr3:/data/db

volumes:
  configsvr1: {}
  configsvr2: {}
  configsvr3: {}
