version: '3'

services:

  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb configsvrrs/<ip>:40001,<ip>:40002,<ip>:40003 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 20000:27017